// frontend/src/components/Navbar.tsx
import { Link } from 'react-router-dom';
import WalletConnect from './WalletConnect';

const Navbar = () => {
  return (
    <nav className="bg-white border-b border-gray-200 px-6 py-4 flex justify-between items-center font-sans fixed w-full top-0 z-50">
      <Link to="/" className="text-red-500 text-xl font-bold">Plume Pawn</Link>
      <div>
        <WalletConnect />
      </div>
    </nav>
  );
};

export default Navbar;

// frontend/src/components/Navbar.vue
<script setup>
import { RouterLink } from 'vue-router'
import WalletConnect from './WalletConnect.vue'
</script>

<template>
    <nav class="bg-white border-b border-gray-200 px-6 py-4 flex justify-between items-center font-sans fixed w-full top-0 z-50">
      <RouterLink to="/" class="text-red-500 text-xl font-bold">Plume Pawn</RouterLink>
      <div>
         <WalletConnect /> 
      </div>
    </nav>
</template>
