// frontend/src/pages/Dashboard.vue
<script setup>

</script>

<template>
  <div class="bg-offwhite">
    <section class="bg-white text-black py-32 px-6 text-center font-sans">
      <h1 class="text-4xl font-bold mb-4">Dashboard</h1>
    </section>
  </div>
</template>

<style scoped>
.bg-offwhite {
  background-color: #F9F9F9;
}
</style>

// frontend/src/pages/Dashboard.tsx
import React from "react"

const Dashboard: React.FC = () => {
  return (
    <div className="bg-[#F9F9F9]">
      <section className="bg-white text-black py-32 px-6 text-center font-sans">
        <h1 className="text-4xl font-bold mb-4">Dashboard</h1>
      </section>
    </div>
  )
}

export default Dashboard
